name: Feature Request
description: Schlage ein neues Feature oder eine Verbesserung vor
title: "[FEATURE]: "
labels: [ "feature" ]
assignees: [ "Huber1" ]
body:
  - type: markdown
    attributes:
      value: "*Bitte 端berpr端fe vor dem erstellen, ob dein Feature-Request schon existiert. Beachte dabei auch geschlossene issues!*"
  - type: textarea
    attributes:
      label: Beschreibe dein Feature
      description: Eine genaue Beschreibung des Features, welches hinzugef端gt werden soll
    validations:
      required: true
  - type: textarea
    attributes:
      label: In wie fern profitiert das Projekt von diesem Feature?
      description: Eine kurze Beschreibung, warum das Feature umgesetzt werden soll
  - type: textarea
    attributes:
      label: Weitere Informationen
      description: Solltest du weitere hilfreiche Infos haben, ist hier der Ort daf端r
  - type: dropdown
    attributes:
      label: "Ich kann dieses Feature selbst implementieren / mithelfen bei der Umsetzung"
      multiple: false
      options: [ "Nein", "Ja" ]
    validations:
      required: true