# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:android)

platform :android do

  desc "Deploy a new internal version to Google Play"
  lane :internal do
    previous_build_number = google_play_track_version_codes(
      package_name: "de.moritzhuber.betterHm",
      track: "internal",
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    )[0]
    current_build_number = previous_build_number + 1
    puts "Previous build number: #{previous_build_number}. Incrementing by 1"
    sh "flutter build appbundle --build-number=#{current_build_number}"
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_changelogs: true,
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    )
  end

  desc "Deploy a new beta version to Google Play"
  lane :beta do
    sh "flutter build appbundle"
    upload_to_play_store(
      track: "beta",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Deploy a new release version to Google Play"
  lane :release do
    sh "flutter build appbundle"
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
