# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:android)

platform :android do
  build_number=nil

  before_all do
    internal = google_play_track_version_codes(
      package_name: "de.moritzhuber.betterHm",
      track: "internal",
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    ).max
    beta = google_play_track_version_codes(
      package_name: "de.moritzhuber.betterHm",
      track: "beta",
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    ).max
    release = google_play_track_version_codes(
      package_name: "de.moritzhuber.betterHm",
      track: "production",
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    ).max
    previous_build_number = [internal, beta, release].max
    puts "Previous build number: #{previous_build_number}. Incrementing by " + ENV["INCREMENT_BUILD_BY"]
    build_number = previous_build_number + ENV["INCREMENT_BUILD_BY"]
  end

  desc "Build and deploy internal release to Google Play"
  lane :internal do
    sh "flutter build appbundle --build-number=#{build_number} --dart-define=\"RELEASE_TYPE=internal\""
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_changelogs: true,
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"]
    )
  end

  desc "Build and deploy beta release to Google Play"
  lane :beta do
    sh "flutter build appbundle --build-number=#{build_number} --dart-define=\"RELEASE_TYPE=beta\""
    upload_to_play_store(
      track: "beta",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"],
      release_status: "draft"
    )
  end

  desc "Build and deploy production release to Google Play"
  lane :release do
    sh "flutter build appbundle --build-number=#{build_number} --dart-define=\"RELEASE_TYPE=production\""
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key_data: ENV["SERVICE_ACCOUNT_JSON"],
      release_status: "draft"
    )
  end
end
