name: Build and publish nightly release

on:
  push:
    branches: [ master ]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  get_build_number:
    name: Get Next Build number
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ env.BUILD_NUMBER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Bundle
        working-directory: android
        run: bundle install

      - name: Bump version
        working-directory: android
        run: bundle exec fastlane build_number
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_JSON }}

  build_mobile:
    name: Build signed binary
    uses: ./.github/workflows/build-release.yml
    needs: get_build_number
    secrets: inherit
    with:
      build_number: ${{ needs.get_build_number.outputs.build_number }}
      artifact_name: nightly-binaries

  release:
    name: Release internal Test
    runs-on: ubuntu-latest
    needs: build_mobile
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: nightly-binaries
          path: binaries

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.moritzhuber.betterHm
          releaseFiles: binaries/**/*.aab
          track: internal
          status: completed