name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      versionBump:
        description: "Bump version"
        required: true
        default: "patch"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-root
  cancel-in-progress: true

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.push-tag.outputs.commit_long_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_RELEASE_TOKEN }}

      - name: Bump version
        run: "tools/bump-version.sh ${{ inputs.versionBump }}"

      - name: Commit and tag
        id: push-tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Moritz Huber
          author_email: 2nd@moritzhuber.de
          default_author: user_info
          message: "Version ${{ env.APP_VERSION }}"
          tag: ${{ env.APP_VERSION }}
          push: true

  build_mobile:
    name: Build signed binary
    uses: ./.github/workflows/build-release.yml
    needs: bump_version
    secrets: inherit
    with:
      ref: ${{ needs.bump_version.outputs.ref }}


  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    needs: build_mobile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_RELEASE_TOKEN }}

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: release-binaries-signed
          path: binaries

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ env.APP_VERSION }}
          files: |
            binaries/**/*.apk
            binaries/**/*.aab

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.moritzhuber.betterHm
          releaseFiles: binaries/**/*.aab
          track: beta
          status: draft