name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      versionBump:
        description: "Bump version"
        required: true
        default: "patch"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"
      title:
        required: false
        type: string
        description: Titel für GitHub Release neben der Versionsnummer
      description:
        required: true
        type: string
        description: Beschreibung für Google Play und GitHub release

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.push-tag.outputs.commit_long_sha }}
      build_number: ${{ env.BUILD_NUMBER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_RELEASE_TOKEN }}

      - name: Bump version
        run: "tools/bump-version.sh ${{ inputs.versionBump }}"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Bundle
        working-directory: android
        run: bundle install

      - name: Get Build Number
        working-directory: android
        run: bundle exec fastlane build_number
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Commit and tag
        id: push-tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Moritz Huber
          author_email: 2nd@moritzhuber.de
          default_author: user_info
          message: "Version ${{ env.APP_VERSION }}"
          tag: ${{ env.APP_VERSION }}
          push: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Bundle
        working-directory: android
        run: bundle install

      - name: Increase Version
        working-directory: android
        run: bundle exec fastlane build_number
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_JSON }}

  build_mobile:
    name: Build signed binary
    uses: ./.github/workflows/build-release.yml
    needs: bump_version
    secrets: inherit
    with:
      build_number: ${{ needs.bump_version.outputs.build_number }}
      ref: ${{ needs.bump_version.outputs.ref }}


  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    needs: build_mobile
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: release-binaries-signed
          path: binaries

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }} ${{ inputs.title }}
          body: ${{ inputs.description }}
          generate_release_notes: true
          make_latest: true
          files: |
            binaries/**/*.apk
            binaries/**/*.aab

      - name: Generate WhatsNew Directory for Google Play
        run: |
          mkdir whatsnew
          echo "${{ inputs.description }}" > whatsnew/whatsnew-de-DE

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.moritzhuber.betterHm
          releaseFiles: binaries/**/*.aab
          whatsNewDirectory: whatsnew
          track: production
          status: completed
